// global variables
const names = ['Name', 'Address', 'Address 2', 'City', 'State', 'Zip', 'Purpose', 'Property Owner', 'Creation Date'];
let code;
let editable;
let message;
let name = true;
let row;
let rowCount = 0;
let errorCount = 0;
let fieldData;
let fieldDate = true;
let fieldErrors;
let fieldNames;
let fieldState = true;
let fieldZip = true;
let firstError;
let fullResults;
let start;
let end;
let firstRun = true;