# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
states = State.create([{ name: 'Alaska', short_name: 'AK' }, { name: 'Alabama', short_name: 'AL' }, { name: 'Arkansas', short_name: 'AR' }, { name: 'American Samoa', short_name: 'AS' }, { name: 'Arizona', short_name: 'AZ' }, { name: 'California', short_name: 'CA' }, { name: 'Colorado', short_name: 'CO' }, { name: 'Connecticut', short_name: 'CT' }, { name: 'District of Columbia', short_name: 'DC' }, { name: 'Delaware', short_name: 'DE' }, { name: 'Florida', short_name: 'FL' }, { name: 'Federated States of Micronesia', short_name: 'FM' }, { name: 'Georgia', short_name: 'GA' }, { name: 'Guam', short_name: 'GU' }, { name: 'Hawaii', short_name: 'HI' }, { name: 'Iowa', short_name: 'IA' }, { name: 'Idaho', short_name: 'ID' }, { name: 'Illinois', short_name: 'IL' }, { name: 'Indiana', short_name: 'IN' }, { name: 'Kansas', short_name: 'KS' }, { name: 'Kentucky', short_name: 'KY' }, { name: 'Louisiana', short_name: 'LA' }, { name: 'Massachusetts', short_name: 'MA' }, { name: 'Maryland', short_name: 'MD' }, { name: 'Maine', short_name: 'ME' }, { name: 'Marshall Islands', short_name: 'MH' }, { name: 'Michigan', short_name: 'MI' }, { name: 'Minnesota', short_name: 'MN' }, { name: 'Missouri', short_name: 'MO' }, { name: 'Northern Mariana Islands', short_name: 'MP' }, { name: 'Mississippi', short_name: 'MS' }, { name: 'Montana', short_name: 'MT' }, { name: 'North Carolina', short_name: 'NC' }, { name: 'North Dakota', short_name: 'ND' }, { name: 'Nebraska', short_name: 'NE' }, { name: 'New Hampshire', short_name: 'NH' }, { name: 'New Jersey', short_name: 'NJ' }, { name: 'New Mexico', short_name: 'NM' }, { name: 'New York', short_name: 'NY' }, { name: 'Nevada', short_name: 'NV' }, { name: 'Ohio', short_name: 'OH' }, { name: 'Oklahoma', short_name: 'OK' }, { name: 'Oregon', short_name: 'OR' }, { name: 'Pennsylvania', short_name: 'PA' }, { name: 'Puerto Rico', short_name: 'PR' }, { name: 'Palau', short_name: 'PW' }, { name: 'Rhode Island', short_name: 'RI' }, { name: 'South Carolina', short_name: 'SC' }, { name: 'South Dakota', short_name: 'SD' }, { name: 'Tennessee', short_name: 'TN' }, { name: 'Texas', short_name: 'TX' }, { name: 'Utah', short_name: 'UT' }, { name: 'Virginia', short_name: 'VA' }, { name: 'Virgin Islands', short_name: 'VI' }, { name: 'Vermont', short_name: 'VT' }, { name: 'Washington', short_name: 'WA' }, { name: 'Wisconsin', short_name: 'WI' }, { name: 'West Virginia', short_name: 'WV' }, { name: 'Wyoming', short_name: 'WY' }])

import = Import.create([{ import_name: 'import01' }])

records = Record.create([{ "Name": 'National Zoological Park', "Address": '3001 Connecticut Ave NW', "Address 2": 'Suite 1001', "City": 'Washington', "State": 'DC', "Zip": '20008', "Purpose": 'Data Center', "Property Owner": 'Smithsonian', "Creation Date": '2018-04-10', "Lat": '38.9296156', "Long": '-77.04978440000002', import_id: Import.last.id }, { "Name": '3Com Corp', "Address": '350 Campus Dr', "Address 2": '', "City": 'Marlborough', "State": 'MA', "Zip": '01752', "Purpose": 'Technology', "Property Owner": '3Com Corp', "Creation Date": '2017-05-04', "Lat": '42.3256103', "Long": '-71.58414069999998', import_id: Import.last.id }, { "Name": 'AG Edwards Inc', "Address": '1 N Jefferson Ave', "Address 2": '', "City": 'St. Louis', "State": 'MO', "Zip": '63103', "Purpose": 'Financials', "Property Owner": 'AG Edwards Inc', "Creation Date": '1887-01-01', "Lat": '38.6312741', "Long": '-90.21581830000002', import_id: Import.last.id }])