CREATE TABLE imports (
	"id" bigserial NOT NULL,
	"import_name" varchar NOT NULL,
	CONSTRAINT imports_pkey PRIMARY KEY ("id"),
    CONSTRAINT imports_import_name_key UNIQUE (import_name)
);

CREATE TABLE states (
    "id" bigserial NOT NULL,
	"name" varchar NOT NULL,
	"short_name" varchar(2) NOT NULL,
    CONSTRAINT states_pkey PRIMARY KEY ("short_name")
);

INSERT INTO states ("short_name", "name") VALUES ('AK', 'Alaska'),
('AL', 'Alabama'),
('AR', 'Arkansas'),
('AS', 'American Samoa'),
('AZ', 'Arizona'),
('CA', 'California'),
('CO', 'Colorado'),
('CT', 'Connecticut'),
('DC', 'District of Columbia'),
('DE', 'Delaware'),
('FL', 'Florida'),
('FM', 'Federated States of Micronesia'),
('GA', 'Georgia'),
('GU', 'Guam'),
('HI', 'Hawaii'),
('IA', 'Iowa'),
('ID', 'Idaho'),
('IL', 'Illinois'),
('IN', 'Indiana'),
('KS', 'Kansas'),
('KY', 'Kentucky'),
('LA', 'Louisiana'),
('MA', 'Massachusetts'),
('MD', 'Maryland'),
('ME', 'Maine'),
('MH', 'Marshall Islands'),
('MI', 'Michigan'),
('MN', 'Minnesota'),
('MO', 'Missouri'),
('MP', 'Northern Mariana Islands'),
('MS', 'Mississippi'),
('MT', 'Montana'),
('NC', 'North Carolina'),
('ND', 'North Dakota'),
('NE', 'Nebraska'),
('NH', 'New Hampshire'),
('NJ', 'New Jersey'),
('NM', 'New Mexico'),
('NV', 'Nevada'),
('NY', 'New York'),
('OH', 'Ohio'),
('OK', 'Oklahoma'),
('OR', 'Oregon'),
('PA', 'Pennsylvania'),
('PR', 'Puerto Rico'),
('PW', 'Palau'),
('RI', 'Rhode Island'),
('SC', 'South Carolina'),
('SD', 'South Dakota'),
('TN', 'Tennessee'),
('TX', 'Texas'),
('UT', 'Utah'),
('VA', 'Virginia'),
('VI', 'Virgin Islands'),
('VT', 'Vermont'),
('WA', 'Washington'),
('WI', 'Wisconsin'),
('WV', 'West Virginia'),
('WY', 'Wyoming');

CREATE TABLE records (
	"id" bigserial NOT NULL,
    "name" varchar NOT NULL,
    "address" varchar NOT NULL,
    "address_2" varchar,
    "city" varchar NOT NULL,
    "state" varchar(2) NOT NULL,
    "zip" varchar(5) NOT NULL,
    "purpose" varchar,
    "property_owner" varchar,
    "creation_date" date NOT NULL,
    "lat" numeric NOT NULL,
    "long" numeric NOT NULL,
	"import_id" bigint NOT NULL,
	CONSTRAINT records_pkey PRIMARY KEY ("id"),
    CONSTRAINT records_import_id_fkey FOREIGN KEY ("import_id")
        REFERENCES imports ("id"),
	CONSTRAINT records_statecode_fkey FOREIGN KEY ("state")
		REFERENCES states ("short_name")
);

WITH get_import_id AS (
	INSERT INTO imports (import_name) VALUES ('import01')
	returning id
)
INSERT INTO records (
	"name",
	"address",
	"address_2",
	"city",
	"state",
	"zip",
	"purpose",
	"property_owner",
	"creation_date",
	"lat",
	"long",
	"import_id"
) VALUES (
	'National Zoological Park',
	'3001 Connecticut Ave NW',
	'Suite 1001',
	'Washington',
	'DC',
	'20008',
	'Data Center',
	'Smithsonian',
	'2018-04-10',
	'38.9296156',
	'-77.04978440000002',
	(SELECT id FROM get_import_id)
),
(
	'3Com Corp',
	'350 Campus Dr',
	'',
	'Marlborough',
	'MA',
	'01752',
	'Technology',
	'3Com Corp',
	'2017-05-04',
	'42.3256103',
	'-71.58414069999998',
	(SELECT id FROM get_import_id)
),
(
	'AG Edwards Inc',
	'1 N Jefferson Ave',
	'',
	'St. Louis',
	'MO',
	'63103',
	'Financials',
	'AG Edwards Inc',
	'1887-01-01',
	'38.6312741',
	'-90.21581830000002',
	(SELECT id FROM get_import_id)
);