let code;
exports.code = code;
let editable;
exports.editable = editable;
let end;
exports.end = end;
let errorCount = 0;
exports.errorCount = errorCount;
let fieldData;
exports.fieldData = fieldData;
let fieldDate = true;
exports.fieldDate = fieldDate;
let fieldErrors;
exports.fieldErrors = fieldErrors;
let fieldNames;
exports.fieldNames = fieldNames;
let fieldState = true;
exports.fieldState = fieldState;
let fieldZip = true;
exports.fieldZip = fieldZip;
let fileName;
exports.fileName = fileName;
let firstError;
exports.firstError = firstError;
let fullResults;
exports.fullResults = fullResults;
let geocoder;
exports.geocoder = geocoder;
let headerCheck = true;
exports.headerCheck = headerCheck;
let infowindow;
exports.infowindow = infowindow;
let lat;
exports.lat = lat;
let long;
exports.long = long;
let map;
exports.map = map;
let mapped = false;
exports.mapped = mapped;
let markers = [];
exports.markers = markers;
let message;
exports.message = message;
let name = true;
exports.name = name;
let pageSwitch = false;
exports.pageSwitch = pageSwitch;
let row;
exports.row = row;
let rowCount = 0;
exports.rowCount = rowCount;
let start;
exports.start = start;
